env:
  name: Digit-v1
  n_envs: 40
  seed: 42

training:
  total_timesteps: 20000000
  learning_rate: 0.0003
  buffer_size: 1000000
  batch_size: 256
  learning_starts: 100
  train_freq: 1
  gradient_steps: 1
  ent_coef: "auto"
  model_save_path: "ppo_digit_model"
  verbose: 1

wandb:
  project: "CoRL2024 L2T Digit"
  run_name: "PPO With new PD gain"
  group: "Digit"
  entity: "fywu"
  sync_tensorboard: True

hydra:
  job:
    chdir: False
