env:
  name: NoisyMujoco-v4
  n_envs: 24
  seed: 42

training:
  teacher_policy_type: "L2TPolicy"
  student_policy_type: "L2TPolicy"
  total_timesteps: 40000000
  learning_rate: 0.0003
  buffer_size: 1000000
  batch_size: 64
  learning_starts: 100
  train_freq: 1
  gradient_steps: 1
  ent_coef: "auto"
  verbose: 0
  log_interval: 1
  progress_bar: True
  mixture_coeff: 0.2

wandb:
  project: "CoRL2024 L2T Digit"
  run_name: "L2T with 200hz, DR0.1"
  group: "Digit"
  entity: "fywu"
  sync_tensorboard: True

hydra:
  job:
    chdir: False
