wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 10000000
env_id:
  desc: null
  value: Cassie-v1
progress_bar:
  desc: null
  value: true
verbose:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0003
_wandb:
  desc: null
  value:
    code_path: code/testing.py
    python_version: 3.10.0
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1688347552.498861
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.10.0
      5: 0.15.4
      8:
      - 4
      - 5
